theme: jekyll-theme-cayman
title: ИТ для школьников
description: Список чтения для желающих попасть в ИТ отрасль
theme: jekyll-theme-cayman
show_downloads: false
locale: ru-RU
words_per_minute: 200
repository: dyakonoff/school_reading_for_it
